apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc-deployment
spec:
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
      - name: discountgrpc-container
        image: acrfortest001.azurecr.io/discountgrpc:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionString__postgresConnectionString
            valueFrom:
              configMapKeyRef:
                name: discountgrpc-configmap
                key: connection-string
      imagePullSecrets:
        - name: acr-secret          
---

apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  selector:
    app: discountgrpc
  ports:
  - port: 80
    protocol: TCP


