apiVersion: v1
kind: ConfigMap
metadata:
  name: orderingapi-configmap
data:
  connection-string: Server=sqldb-service;Database=OrderDb;User Id=sa;Password=Admin1234;
  broker-host-address: amqp://guest:guest@rabitmq-service:5672