apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb-deployment
  labels:
    app: sqldb
spec:
  selector:
    matchLabels:
      app: sqldb
  template:
    metadata:
      labels:
        app: sqldb
    spec:
      containers:
      - name: sqldb-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "0.2"          
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqldb-secret
              key: sa-password
        - name: ACCEPT_EULA
          value: "Y"
      #   volumeMounts:
      #   - name: mssqldb
      #     mountPath: /var/opt/mssql
      # volumes:
      # - name: mssqldb
      #   persistentVolumeClaim:
      #     claimName: mssql-data-2  

---

apiVersion: v1
kind: Service
metadata:
  name: sqldb-service
spec:
  selector:
    app: sqldb
  ports:
  - protocol: TCP
    port: 1433
