apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
spec:
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
      - name: basketapi-container
        image: acrfortest001.azurecr.io/basketapi:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "64Mi"
            cpu: "0.3"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: EventBusSettings__HostAddress
            valueFrom:
              configMapKeyRef:
                name: basketapi-configmap
                key: broker-host-address 
          - name: CashSettings__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: basketapi-configmap
                key: connection-string
          - name: GrpcSettings__DiscountGrpcUrl
            valueFrom:
              configMapKeyRef:
                name: basketapi-configmap
                key: discount-grpc-url
      imagePullSecrets:
        - name: acr-secret          
---

apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  selector:
    app: basketapi
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80


