apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
spec:
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
      - name: discountapi-container
        image: acrfortest001.azurecr.io/discountapi:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "64Mi"
            cpu: "0.3"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionString__postgresConnectionString
            valueFrom:
              configMapKeyRef:
                name: discountapi-configmap
                key: connection-string
      imagePullSecrets:
        - name: acr-secret          
---

apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  selector:
    app: discountapi
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 80


