apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregatorapi-deployment
spec:
  selector:
    matchLabels:
      app: shoppingaggregatorapi
  template:
    metadata:
      labels:
        app: shoppingaggregatorapi
    spec:
      containers:
      - name: shoppingaggregatorapi-container
        image: acrfortest001.azurecr.io/shoppingaggregatorapi:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "64Mi"
            cpu: "0.3"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ApiSettings__CatalogApiUrl
            valueFrom:
              configMapKeyRef:
                name: shoppingaggregatorapi-configmap
                key: catalogapi-url
          - name: ApiSettings__BasketApiUrl
            valueFrom:
              configMapKeyRef:
                name: shoppingaggregatorapi-configmap
                key: basketapi-url
          - name: ApiSettings__OrderApiUrl
            valueFrom:
              configMapKeyRef:
                name: shoppingaggregatorapi-configmap
                key: orderapi-url      
      imagePullSecrets:
        - name: acr-secret          
---

apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregatorapi-service
spec:
  type: NodePort
  selector:
    app: shoppingaggregatorapi
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 80
    nodePort: 31001


